name: Streamlit Deploy

on:
  push:
    branches:
      - master  # Change this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'   
  # Specify the exact version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > google-cloud-api-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/google-cloud-api-key.json

      - name: Run Streamlit
        run: |
          streamlit run env_monitoring.py
